### ISSUE TITLE
Oldprodigyde's WalkSpeed Mod

### ISSUE THREAD

**Issue by XPMUser** [XPMUser/XPMUser.github.io#79]
### What went wrong?

My body was broken when I tried to walk. WalkableScreen.prototype.listener = function

### Which version?

1.16.5 Definitive Edition

### How can I reproduce this?

Walk with a WalkSpeed Mod

### What did the logs output? (press F12 or CTRL+SHIFT+J to see console logs)

[]
30
Microsoft Edge is moving towards a new experience that allows users to choose to browse without third-party cookies.
controls.min.js:30    Macaron v | Pictograph Fix & Effectiveness Tracking   
public.min.js:14 
 
 GET http://localhost/controls.css net::ERR_ABORTED 404 (Not Found)
public.min.js:15 
 
 GET https://s3.amazonaws.com/prodigy-assets/education/skills/prod/b47b674f96/skillTrees.json 403 (Forbidden)
public.min.js:15 
 
 GET https://s3.amazonaws.com/prodigy-assets/education/skills/prod/b47b674f96/curricula.json 403 (Forbidden)
question.min.js:13    QI v2.2.10 | Effectiveness Tracking   
question.min.js:13 
{}
question.min.js:13 
 Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at Prodigy.Curriculum.getCurriculum (question.min.js:13:9871)
    at Prodigy.Curriculum.processSkills (question.min.js:13:9435)
    at Prodigy.SkillSelection.setState (question.min.js:13:13675)
    at new Prodigy.SkillSelection (question.min.js:13:13292)
    at Prodigy.EducationSystem.init (question.min.js:13:10881)
    at new Prodigy.EducationSystem (question.min.js:13:10726)
    at question.min.js:15:15074
    at question.min.js:15:15945
phaser.min.js:4 
 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
pageScript.js:85 timeout   100
pageScript.js:85 timeout   1000
game.min.js:53515    Prodigy Definitive Edition version 2.1.0 | 1.16.5 Mode   
mod-handler.js:59    Checking for mods...   
mod-handler.js:59    Mod "WalkSpeed" successfully applied!   
mod-handler.js:59    Mod "FastGameSpeed" successfully applied!   
mod-handler.js:67    Error occured while applying mod "ClassicFaces" to Prodigy!   
mod-handler.js:297 
 TypeError: Cannot read properties of undefined (reading 'getAssetMap')
    at ModHandler.initClassicFaceMod (mod-handler.js:149:33)
    at window.checkForMods (mod-handler.js:295:17)
    at Boot.init (game.min.js:41903:3)
    at window.onload (oldprodigyde/?mods=W…ClassicFaces:205:22)
mod-handler.js:59    Applied (2) mods to the game   
phaser.min.js:4 
 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
phaser.min.js:4    Phaser v2.2.2 | Pixi.js v2.2.0 | Canvas | WebAudio     http://phaser.io ♥♥♥
mod-handler.js:63    Use "setGameSpeed(speed)" to change the game speed at anytime.   
game.min.js:41935 loaded true
pageScript.js:85 timeout   13
pageScript.js:85 timeout   13
game.min.js:41935 loaded true
pageScript.js:29 
(4) [{…}, {…}, {…}, {…}]
pageScript.js:29 
(2) [{…}, {…}]
pageScript.js:29 
(2) [{…}, {…}]
pageScript.js:29 
(2) [{…}, {…}]
pageScript.js:29 
(2) [{…}, {…}]
pageScript.js:29 
(2) [{…}, {…}]
pageScript.js:29 
(2) [{…}, {…}]
pageScript.js:29 
(2) [{…}, {…}]
game.min.js:41935 loaded true
pageScript.js:29 
(2) [{…}, {…}]
pageScript.js:29 
(2) [{…}, {…}]
game.min.js:35729 {"userID":4,"appearance":{"name":"Alexis Sleepgem","gender":"female","hairStyle":19,"hairColor":2,"skinColor":3,"eyeColor":6,"x":800,"y":700},"data":{},"equipment":{"hat":64,"weapon":55,"outfit":51}}
pageScript.js:29 
(2) [{…}, {…}]

### I agree to the following

- [X] By checking this box, I confirm that this bug report is being made for a bug that occurred on THIS website (xpmuser.github.io), and NOT these websites (daboss7173.github.io / oldprodigy.onrender.com)
- [X] By checking this box, I confirm that this issue is being used to report a problem with an existing feature, and not to suggest a new feature.
- [X] By checking this box, I confirm that this issue is being used to report an honest problem with an existing feature.

**Comment by XPMUser** [comment]
Letter struggles
